### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by ganler** [favyen/miris#4]
Hi @uakfdotb , thanks for your great work!

It seems that the FFmpeg command generates frames whose index starts from 1. Which is not compatible with the ground truth label index of the YTStreamDataset (which starts from 0).

![image](https://user-images.githubusercontent.com/38074777/99903635-7a4c4200-2d00-11eb-83bd-00121d219170.png)

So I wonder if it will break the logic of the codes if I simply add `frame_idx += 1` here(https://github.com/favyen/miris/blob/master/models/gnn/train.py#L203).

**Comment by uakfdotb** [comment]
Thanks for opening issue. For shibuya/warsaw/beach videos 1,2,3,4,5 (not 0), the frames are supposed to start from 000000.jpg due to how they were originally extracted, but extract.py was starting it at 000001.jpg. I think you can change code like that as long as detections[0] corresponds 000001.jpg (which should be 000000.jpg).

I pushed update to data/extract.py which should fix the issue. It will re-number the extracted frames where needed.

**Comment by ganler** [comment]
@uakfdotb Great! Thanks!
